[package]
name = "knex-selection-challenges"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
serde = { version = "1.0.219", features = ["derive"] }
diesel = { version = "2.2.0", features = ["postgres"] }
dotenvy = "0.15"