[package]
name = "knex-selection-challenges"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
serde = { version = "1.0.219", features = ["derive"] }
diesel = { version = "2.2.0", features = ["postgres", "chrono"] }
dotenvy = "0.15"
chrono = "0.4.41"
anyhow = "1.0.98"
actix-web = "4"